#!/bin/bash
set -e

echo "🐚 Coralline 安装脚本"
echo "======================"
echo ""

# 步骤 1: 检查前置条件
echo "📋 步骤 1/5: 检查前置条件..."
command -v jq >/dev/null 2>&1 || { echo "❌ 需要 jq，请先安装: brew install jq"; exit 1; }
echo "   ✅ jq 已安装"
echo "   ✅ bash $(bash --version | head -1 | grep -oE '[0-9]+\.[0-9]+\.[0-9]+')"

# 步骤 3: 下载文件
echo ""
echo "📥 步骤 2/5: 下载文件..."
mkdir -p ~/.claude/coralline/themes
BASE="https://raw.githubusercontent.com/Nanako0129/coralline/main"
curl -fsSL "$BASE/statusline.sh" -o ~/.claude/coralline/statusline.sh
curl -fsSL "$BASE/themes/claude-coral.conf" -o ~/.claude/coralline/themes/claude-coral.conf
chmod +x ~/.claude/coralline/statusline.sh
echo "   ✅ statusline.sh 已下载"
echo "   ✅ claude-coral 主题已下载"

# 步骤 4: 生成配置文件
echo ""
echo "⚙️  步骤 3/5: 生成配置文件..."
DATE=$(date "+%Y-%m-%d %H:%M")
cat > ~/.claude/coralline.conf << 'EOF'
# coralline config — generated by AI installer on INSTALL_DATE
. ~/.claude/coralline/themes/claude-coral.conf

VL_STYLE="pill"
VL_LAYOUT="auto"
VL_MAX_LINES=3
VL_WRAP_MARGIN=4
VL_SEGMENTS="dir git model ctx limit5h limit7d cost clock"
VL_SEGMENTS2=""
VL_SEGMENTS3=""
VL_CLOCK="24h"
VL_CLOCK_SECONDS=1
VL_BAR_WIDTH=5
VL_COST_DECIMALS=2
VL_PATH_DEPTH=4
VL_NAME_MAX=0
VL_ASCII=0
EOF
sed -i '' "s/INSTALL_DATE/$DATE/" ~/.claude/coralline.conf
echo "   ✅ 配置文件已生成: ~/.claude/coralline.conf"

# 步骤 5: 更新 settings.json
echo ""
echo "🔧 步骤 4/5: 更新 settings.json..."
if [ -f ~/.claude/settings.json ]; then
    cp ~/.claude/settings.json ~/.claude/settings.json.bak
    echo "   ✅ 已备份 settings.json"
else
    echo "   ℹ️  settings.json 不存在，将创建新文件"
fi

# 合并 statusLine 配置
if [ -f ~/.claude/settings.json ]; then
    jq '.statusLine = {
        "type": "command",
        "command": "bash ~/.claude/coralline/statusline.sh",
        "refreshInterval": 1
    }' ~/.claude/settings.json > /tmp/settings_coralline.json && mv /tmp/settings_coralline.json ~/.claude/settings.json
else
    echo '{"statusLine":{"type":"command","command":"bash ~/.claude/coralline/statusline.sh","refreshInterval":1}}' | jq '.' > ~/.claude/settings.json
fi
echo "   ✅ statusLine 配置已写入 settings.json"

# 步骤 6: 验证
echo ""
echo "🧪 步骤 5/5: 验证安装..."
if curl -fsSL "$BASE/test/sample-input.json" | bash ~/.claude/coralline/statusline.sh > /tmp/coralline-test.txt 2>/tmp/coralline-err.txt; then
    echo "   ✅ 状态行运行正常!"
    echo ""
    echo "══════════════════════════════════════════"
    echo "  🎉 Coralline 安装完成!"
    echo "══════════════════════════════════════════"
    echo ""
    echo "配置摘要:"
    echo "  主题:     claude-coral"
    echo "  样式:     pill (Powerline 胶囊)"
    echo "  布局:     auto (响应式, 最大3行)"
    echo "  时钟:     24小时制"
    echo "  分段:     dir git model ctx limit5h limit7d cost clock"
    echo "  字体:     Nerd Font"
    echo ""
    echo "状态行将在 Claude Code 下次重启或新会话中生效。"
    echo ""
else
    echo "   ⚠️  验证未通过，请检查 /tmp/coralline-test.txt 和 /tmp/coralline-err.txt"
    exit 1
fi
