import type { NotificationType, PostCategory } from "@/lib/types";
import {
  ArrowLeft,
  ArrowRight,
  Bell,
  BrainCircuit,
  Building2,
  ChartNoAxesColumn,
  Check,
  ChevronRight,
  ChevronUp,
  Clock3,
  Copy,
  Expand,
  FileText,
  Globe,
  HandHelping,
  Heart,
  House,
  ImagePlus,
  Info,
  Lock,
  LogOut,
  Megaphone,
  MessageCircle,
  MessagesSquare,
  MoreHorizontal,
  PartyPopper,
  Pencil,
  Plus,
  Search,
  Settings2,
  Share2,
  ShieldCheck,
  ShoppingBag,
  SlidersHorizontal,
  SquarePen,
  Star,
  ThumbsUp,
  Ticket,
  User,
  UserPlus,
  Users,
  Vote,
  Wrench,
  X,
} from "lucide-react";

export {
  ArrowLeft as ArrowLeftIcon,
  ArrowRight as ArrowRightIcon,
  Bell as BellIcon,
  BrainCircuit as BrainCircuitIcon,
  Building2 as BuildingIcon,
  ChartNoAxesColumn as ChartIcon,
  Check as CheckIcon,
  ChevronRight as ChevronRightIcon,
  ChevronUp as ChevronUpIcon,
  Clock3 as ClockIcon,
  Copy as CopyIcon,
  Expand as ExpandIcon,
  FileText as FileTextIcon,
  Globe as GlobeIcon,
  Heart as HeartIcon,
  House as HomeIcon,
  House as HomeLineIcon,
  ImagePlus as ImagePlusIcon,
  Info as InfoIcon,
  Lock as LockIcon,
  Lock as LockLineIcon,
  LogOut as LogoutIcon,
  MessageCircle as CommentIcon,
  MessagesSquare as MessagesIcon,
  MoreHorizontal as MoreHorizontalIcon,
  Pencil as EditIcon,
  Plus as PlusIcon,
  Search as SearchIcon,
  Settings2 as SettingsIcon,
  Share2 as ShareIcon,
  ShieldCheck as ShieldIcon,
  SlidersHorizontal as FilterIcon,
  SquarePen as PublishIcon,
  Star as StarIcon,
  ThumbsUp as ThumbsUpIcon,
  Ticket as InviteIcon,
  Ticket as TicketIcon,
  User as UserIcon,
  User as UserLineIcon,
  UserPlus as UserPlusIcon,
  Users as UsersIcon,
  Vote as VoteIcon,
  Wrench as ServiceIcon,
  Wrench as WrenchIcon,
  X as CloseIcon,
};

export const postCategoryIconMap = {
  request: HandHelping,
  secondhand: ShoppingBag,
  discussion: MessagesSquare,
  play: PartyPopper,
} satisfies Record<PostCategory, typeof HandHelping>;

export const notificationIconMap = {
  comment: MessageCircle,
  favorite: Star,
  poll: ChartNoAxesColumn,
  ticket: Wrench,
  system: Bell,
} satisfies Record<NotificationType, typeof MessageCircle>;

export const serviceActionIconMap = {
  repair: Wrench,
  complaint: Megaphone,
  facility: Building2,
  discussion: FileText,
} as const;
